### ISSUE TITLE
DB generation

### ISSUE THREAD

**Issue by gedw99** [Boostport/address#37]
For example you create a User in the DB and then want to record their address, but use a lookup table for Country, City.

Everyone uses different DB and DAL, so maybe we can generate a DB CSV as part of the gen process.

I use Ent, because I am lazy :) But it does work well with atlas. So from a CSV I can write a bit of code to manage that.

**Comment by F21** [comment]
Can you elaborate further on how this would be implemented? Should we generate a CSV file of the data and include it in the repository? If we were to have 1 row per country in the CSV file (see [data format](https://github.com/Boostport/address?tab=readme-ov-file#address-data-format)), some of the values won't be pure strings and will have a more complex shape.

I have not used Ent or atlas, so I am trying to visualize how this should be implemented. There are currently [some methods to look up the internal data](https://github.com/Boostport/address?tab=readme-ov-file#address-data-format) should we add more methods to support your use-case instead of publishing a CSV?

**Comment by gedw99** [comment]
Hey @F21 

Thanks for considering my request. Hopefully its something that is useful for you and others ?

I think a CSV is a smart first move because then anyone can use it with whatever DB system they have. I work on ENT but also SQLC for example. 

It should be done IMHO when the code gen happen.

We can also hardcode the SQL table creations and queries into the repo.

With the CVS and the SQL, users can then easily see how to use it with any DB driver. They just need to do a little bit of work to integrate it. 

I might even write SQLC and ENT code to do that last bit of it eventually, but you don't want any of those dependencies polluting this repo is my point.

what ya think ?

**Comment by gedw99** [comment]
I just it this links you sent.   I have to run to a meeting, but if we get the CSV data out for now, then we can look at the code related to the DAL, because I think its the DAL layer where you are asking for advice. Basically how to Mao the golang entities to the DB structure.

**Comment by F21** [comment]
I think generating a bunch of CSV files and providing SQL schemas goes beyond the scope for this library. I'd like to keep this library scoped to being an address verification and formatting library for Go, with some ability to access the internal data using a few simple functions.

I believe what you're looking for is more generalized and perhaps, you can fork this project and update the generator to generate those CSV files for you (the project is licensed under Apache 2.0).

**Comment by gedw99** [comment]
Ok fair enough …

**Comment by F21** [comment]
I'll go ahead an close this for now.
